documents:
  - description: Configuration System
    outputPath: core/config-loader.md
    sources:
      - type: file
        sourcePaths:
          - .
          - ../Document
          - ../Fetcher
          - ../Application/Bootloader/ConfigLoaderBootloader.php
          - ../Application/Bootloader/ImportBootloader.php

  - description: Configuration Parser
    outputPath: core/config-parser.md
    sources:
      - type: file
        sourcePaths:
          - ./Parser

