documents:
  - description: Configuration System
    outputPath: core/config-loader.md
    sources:
      - type: file
        sourcePaths:
          - .
          - ../Document
          - ../Fetcher
        filePattern: '*.php'
        showTreeView: true

